name: Go Dependency Submission
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  go-dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run snapshot action
        uses: actions/go-dependency-submission@v2
        with:
          go-mod-path: go.mod
